[package]
name = "sorts"
version = "0.1.0"
authors = ["Michael Mezzina <michaelmez39@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.3"
plotters = "0.2.12"
rayon = "1.3.0"